//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC.UnifaunOnline.UnifaunAuth {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.unifaun.se/ws/Authentication2")]
    public partial class wsFaultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorExtraField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorExtra {
            get {
                return this.errorExtraField;
            }
            set {
                this.errorExtraField = value;
                this.RaisePropertyChanged("errorExtra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifaun.se/ws/Authentication2", ConfigurationName="UnifaunAuth.Authentication2")]
    public interface Authentication2 {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Login1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ITC.UnifaunOnline.UnifaunAuth.wsFaultInfo), Action="urn:Login1", Name="WSException", Namespace="http://www.unifaun.se/ws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ITC.UnifaunOnline.UnifaunAuth.Login1Response Login1(ITC.UnifaunOnline.UnifaunAuth.Login1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login1", WrapperNamespace="http://www.unifaun.se/ws/Authentication2", IsWrapped=true)]
    public partial class Login1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/Authentication2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/Authentication2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/Authentication2", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string developerId;
        
        public Login1() {
        }
        
        public Login1(string userId, string pass, string developerId) {
            this.userId = userId;
            this.pass = pass;
            this.developerId = developerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login1Response", WrapperNamespace="http://www.unifaun.se/ws/Authentication2", IsWrapped=true)]
    public partial class Login1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/Authentication2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Login1Response() {
        }
        
        public Login1Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Authentication2Channel : ITC.UnifaunOnline.UnifaunAuth.Authentication2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Authentication2Client : System.ServiceModel.ClientBase<ITC.UnifaunOnline.UnifaunAuth.Authentication2>, ITC.UnifaunOnline.UnifaunAuth.Authentication2 {
        
        public Authentication2Client() {
        }
        
        public Authentication2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Authentication2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Authentication2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Authentication2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITC.UnifaunOnline.UnifaunAuth.Login1Response ITC.UnifaunOnline.UnifaunAuth.Authentication2.Login1(ITC.UnifaunOnline.UnifaunAuth.Login1 request) {
            return base.Channel.Login1(request);
        }
        
        public string Login1(string userId, string pass, string developerId) {
            ITC.UnifaunOnline.UnifaunAuth.Login1 inValue = new ITC.UnifaunOnline.UnifaunAuth.Login1();
            inValue.userId = userId;
            inValue.pass = pass;
            inValue.developerId = developerId;
            ITC.UnifaunOnline.UnifaunAuth.Login1Response retVal = ((ITC.UnifaunOnline.UnifaunAuth.Authentication2)(this)).Login1(inValue);
            return retVal.@return;
        }
    }
}
