//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC.UnifaunOnline.UnifaunTrackBackDiscard {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.unifaun.se/ws/History3")]
    public partial class wsFaultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorExtraField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorExtra {
            get {
                return this.errorExtraField;
            }
            set {
                this.errorExtraField = value;
                this.RaisePropertyChanged("errorExtra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifaun.se/ws/History3", ConfigurationName="UnifaunTrackBackDiscard.History3")]
    public interface History3 {
        
        // CODEGEN: Parameter 'session' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:DiscardShipments1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ITC.UnifaunOnline.UnifaunTrackBackDiscard.wsFaultInfo), Action="urn:DiscardShipments1", Name="WSException", Namespace="http://www.unifaun.se/ws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ITC.UnifaunOnline.UnifaunTrackBackDiscard.DiscardShipments1Response DiscardShipments1(ITC.UnifaunOnline.UnifaunTrackBackDiscard.DiscardShipments1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:FetchNewShipments1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ITC.UnifaunOnline.UnifaunTrackBackDiscard.wsFaultInfo), Action="urn:FetchNewShipments1", Name="WSException", Namespace="http://www.unifaun.se/ws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ITC.UnifaunOnline.UnifaunTrackBackDiscard.FetchNewShipments1Response FetchNewShipments1(ITC.UnifaunOnline.UnifaunTrackBackDiscard.FetchNewShipments1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DiscardShipments1", WrapperNamespace="http://www.unifaun.se/ws/History3", IsWrapped=true)]
    public partial class DiscardShipments1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/History3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/History3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("identifiers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] identifiers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/History3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identifierType;
        
        public DiscardShipments1() {
        }
        
        public DiscardShipments1(string session, string[] identifiers, string identifierType) {
            this.session = session;
            this.identifiers = identifiers;
            this.identifierType = identifierType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DiscardShipments1Response", WrapperNamespace="http://www.unifaun.se/ws/History3", IsWrapped=true)]
    public partial class DiscardShipments1Response {
        
        public DiscardShipments1Response() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.unifaun.se/ws/History3")]
    public partial class fetchNewShipmentsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool doneField;
        
        private long fetchIdField;
        
        private long minDelayField;
        
        private fetchNewShipmentsResultShipment[] shipmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool done {
            get {
                return this.doneField;
            }
            set {
                this.doneField = value;
                this.RaisePropertyChanged("done");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long fetchId {
            get {
                return this.fetchIdField;
            }
            set {
                this.fetchIdField = value;
                this.RaisePropertyChanged("fetchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long minDelay {
            get {
                return this.minDelayField;
            }
            set {
                this.minDelayField = value;
                this.RaisePropertyChanged("minDelay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public fetchNewShipmentsResultShipment[] shipments {
            get {
                return this.shipmentsField;
            }
            set {
                this.shipmentsField = value;
                this.RaisePropertyChanged("shipments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.unifaun.se/ws/History3")]
    public partial class fetchNewShipmentsResultShipment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNoField;
        
        private int parcelCountField;
        
        private string[] parcelNosField;
        
        private string partnerIdField;
        
        private System.DateTime printDateField;
        
        private bool printDateFieldSpecified;
        
        private string referenceField;
        
        private string serviceIdField;
        
        private System.DateTime shipDateField;
        
        private bool shipDateFieldSpecified;
        
        private string shipmentNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int parcelCount {
            get {
                return this.parcelCountField;
            }
            set {
                this.parcelCountField = value;
                this.RaisePropertyChanged("parcelCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parcelNos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] parcelNos {
            get {
                return this.parcelNosField;
            }
            set {
                this.parcelNosField = value;
                this.RaisePropertyChanged("parcelNos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string partnerId {
            get {
                return this.partnerIdField;
            }
            set {
                this.partnerIdField = value;
                this.RaisePropertyChanged("partnerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime printDate {
            get {
                return this.printDateField;
            }
            set {
                this.printDateField = value;
                this.RaisePropertyChanged("printDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool printDateSpecified {
            get {
                return this.printDateFieldSpecified;
            }
            set {
                this.printDateFieldSpecified = value;
                this.RaisePropertyChanged("printDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime shipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
                this.RaisePropertyChanged("shipDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shipDateSpecified {
            get {
                return this.shipDateFieldSpecified;
            }
            set {
                this.shipDateFieldSpecified = value;
                this.RaisePropertyChanged("shipDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string shipmentNo {
            get {
                return this.shipmentNoField;
            }
            set {
                this.shipmentNoField = value;
                this.RaisePropertyChanged("shipmentNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchNewShipments1", WrapperNamespace="http://www.unifaun.se/ws/History3", IsWrapped=true)]
    public partial class FetchNewShipments1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/History3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/History3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long fetchId;
        
        public FetchNewShipments1() {
        }
        
        public FetchNewShipments1(string session, long fetchId) {
            this.session = session;
            this.fetchId = fetchId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchNewShipments1Response", WrapperNamespace="http://www.unifaun.se/ws/History3", IsWrapped=true)]
    public partial class FetchNewShipments1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unifaun.se/ws/History3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ITC.UnifaunOnline.UnifaunTrackBackDiscard.fetchNewShipmentsResult @return;
        
        public FetchNewShipments1Response() {
        }
        
        public FetchNewShipments1Response(ITC.UnifaunOnline.UnifaunTrackBackDiscard.fetchNewShipmentsResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface History3Channel : ITC.UnifaunOnline.UnifaunTrackBackDiscard.History3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class History3Client : System.ServiceModel.ClientBase<ITC.UnifaunOnline.UnifaunTrackBackDiscard.History3>, ITC.UnifaunOnline.UnifaunTrackBackDiscard.History3 {
        
        public History3Client() {
        }
        
        public History3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public History3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public History3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public History3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITC.UnifaunOnline.UnifaunTrackBackDiscard.DiscardShipments1Response ITC.UnifaunOnline.UnifaunTrackBackDiscard.History3.DiscardShipments1(ITC.UnifaunOnline.UnifaunTrackBackDiscard.DiscardShipments1 request) {
            return base.Channel.DiscardShipments1(request);
        }
        
        public void DiscardShipments1(string session, string[] identifiers, string identifierType) {
            ITC.UnifaunOnline.UnifaunTrackBackDiscard.DiscardShipments1 inValue = new ITC.UnifaunOnline.UnifaunTrackBackDiscard.DiscardShipments1();
            inValue.session = session;
            inValue.identifiers = identifiers;
            inValue.identifierType = identifierType;
            ITC.UnifaunOnline.UnifaunTrackBackDiscard.DiscardShipments1Response retVal = ((ITC.UnifaunOnline.UnifaunTrackBackDiscard.History3)(this)).DiscardShipments1(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITC.UnifaunOnline.UnifaunTrackBackDiscard.FetchNewShipments1Response ITC.UnifaunOnline.UnifaunTrackBackDiscard.History3.FetchNewShipments1(ITC.UnifaunOnline.UnifaunTrackBackDiscard.FetchNewShipments1 request) {
            return base.Channel.FetchNewShipments1(request);
        }
        
        public ITC.UnifaunOnline.UnifaunTrackBackDiscard.fetchNewShipmentsResult FetchNewShipments1(string session, long fetchId) {
            ITC.UnifaunOnline.UnifaunTrackBackDiscard.FetchNewShipments1 inValue = new ITC.UnifaunOnline.UnifaunTrackBackDiscard.FetchNewShipments1();
            inValue.session = session;
            inValue.fetchId = fetchId;
            ITC.UnifaunOnline.UnifaunTrackBackDiscard.FetchNewShipments1Response retVal = ((ITC.UnifaunOnline.UnifaunTrackBackDiscard.History3)(this)).FetchNewShipments1(inValue);
            return retVal.@return;
        }
    }
}
